[package]
name = "tree-statistics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indextree = { version = "4.6.0", features = ["default", "rayon", "par_iter"]}
